import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import { Providers } from './Utils/Redux/provider';
import NavBar from "./Components/navBar/navBar";
import { App as AntdApp, ConfigProvider } from 'antd';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AntdApp>
            <NavBar />
            {children}
          </AntdApp>
        </Providers>
      </body>
    </html>
  );
}
